#
# Module manifest for module 'EzFirewallMgmt'
#
# Generated by: JJ Fullmer
#
# Generated on: 8/3/2020
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'EzFirewallMgmt.psm1'

# Version number of this module.
ModuleVersion = '1.0.47.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'ea9e45e7-22dc-43ff-85db-c81d02899aa2'

# Author of this module
Author = 'JJ Fullmer'

# Company or vendor of this module
CompanyName = 'DarkSidePwnGramming'

# Copyright statement for this module
Copyright = '2020'

# Description of the functionality provided by this module
Description = 'Simplified helper functions to block and unblock ports and programs
Utilizes New-NetFirewallRule and Remove-NetFirewallRule functions and turns them into easier versions'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '3.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-PortRule', 'Add-ProgramRule', 'Block-Port', 'Block-Program', 
               'Get-ExePaths', 'Get-PortRuleName', 'Get-ProgramRuleName', 
               'Remove-PortRule', 'Remove-ProgramRule', 'Unblock-Port', 
               'Unblock-Program'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Firewall','Windows-Firewall','Windows-control-panel','Windows-Defender','Firewall-Management','Admin-Tools','Security','networkSecurity','network'

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/darksidemilk/EzFirewallMgmt/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/darksidemilk/EzFirewallMgmt'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
# 1.0.47.1

	added progress bars and modular functions for adding rules to make code a bit cleaner

# 1.0.40.2

	Made it so pipeline variables can be used for paths with examples of filtered get-exepaths output being piped in to show how you could select exes for a program name

# 1.0.22.18

	Got pipeline working correctly

# 1.0.22.17

	testing different begin/process/end order

# 1.0.22.16

	testing different begin/process/end order

# 1.0.22.15

	testing different begin/process/end order

# 1.0.22.14

	testing different begin/process/end order

# 1.0.22.13

	testing different begin/process/end order

# 1.0.22.12

	testing different begin/process/end order

# 1.0.22.11

	testing additional parameter settings

# 1.0.22.10

	testing additional parameter settings

# 1.0.22.9

	adjusted process blocks so pipeline can work proper

# 1.0.22.8

	adjusted process blocks so pipeline can work proper

# 1.0.22.7

	adjusted process blocks so pipeline can work proper

# 1.0.22.6

	dont specify type for path

# 1.0.22.5

	added debug lines

# 1.0.22.4

	trying path var as fileinfo object for pipeline

# 1.0.22.3

	Added pipeline input for bypath with examples for using a whereobject pipe on get-exepaths

# 1.0.22.2

	Added pipeline input for bypath with examples for using a whereobject pipe on get-exepaths

# 1.0.22.1

	Tested and confirmed that unblock/block program by name function is actually working as ecpected now  and rebuilding before publishing with new version build number

# 1.0.10.12

	Created new function for getting exe paths separately and made sure each index of the list was a single path not a group of paths

# 1.0.10.11

	Adding debug lines to figure out why programrules arent creating

# 1.0.10.10

	Use -Filter "*.exe" not -include when finding all exes with get-childitem

# 1.0.10.9

	Use -Filter "*.exe" not -include when finding all exes with get-childitem

# 1.0.10.8

	Use -Filter "*.exe" not -include when finding all exes with get-childitem

# 1.0.10.7

	Fix default programname setting to only occur when that paramterset is used when blocking/unblocking a program

# 1.0.10.6

	publishing build

# 1.0.10.5

	updated build script to specify powershell version too

# 1.0.10.4

	updated build script to include more manifest info

# 1.0.10.3

	Made an about help file and a readthedocs index file. Now for sure ready to publish to the gallery

# 1.0.10.2

	Updated readme and release notes with formatting. Added more intro information inf readme. Got module ready for publishing to psgallery completely

# 1.0.10.1

	general updates and bug fixes

# 1.0.0.9

    Added Help Documentation to each function and fixed some typos

# 1.0.0.1

    Initial Release
'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://ezfirewallmgmt.readthedocs.io/en/latest/'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

